In [3]:
import pandas as pd
import sqlite3

In [4]:
#Loading Data from CSV Files
providers = pd.read_csv("/Users/keerthi/Desktop/Andrea Python/datasets/providers_data.csv")
receivers = pd.read_csv("/Users/keerthi/Desktop/Andrea Python/datasets/receivers_data.csv")
food_listings = pd.read_csv("/Users/keerthi/Desktop/Andrea Python/datasets/food_listings_data.csv")
claims = pd.read_csv("/Users/keerthi/Desktop/Andrea Python/datasets/claims_data.csv")

In [5]:
print(providers.info())
print(receivers.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Provider_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   Address      1000 non-null   object
 4   City         1000 non-null   object
 5   Contact      1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Receiver_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   City         1000 non-null   object
 4   Contact      1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB
None

In [6]:
print(food_listings.info())
print(claims.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   object
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   object
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   object
 6   Location       1000 non-null   object
 7   Food_Type      1000 non-null   object
 8   Meal_Type      1000 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   object
 4   Timestamp    1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB
None

In [7]:
# Dataabase Connection
conn = sqlite3.connect("food_waste_management.db")
cursor = conn.cursor()

In [8]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS providers(
        provider_ID INT PRIMARY KEY,
        Name VARCHAR(300),
        Type VARCHAR(100),
        Address TEXT,
        City VARCHAR(100),
        Contact VARCHAR(50)
    )
""")
conn.commit()

In [9]:
for index, row in providers.iterrows():
    cursor.execute("""
        INSERT OR IGNORE INTO providers (Provider_ID, Name, Type, Address, City, Contact)
        VALUES (?, ?, ?, ?, ?, ?)
    """, (row['Provider_ID'], row['Name'], row['Type'], row['Address'], row['City'], row['Contact']))

conn.commit()

In [10]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS receivers(
        Receiver_ID INT PRIMARY KEY,
        Name VARCHAR(300),
        Type VARCHAR(100),
        City VARCHAR(100),
        Contact VARCHAR(50)
    )
""")
conn.commit()

In [11]:
for index, row in receivers.iterrows():
    cursor.execute("""
        INSERT OR IGNORE INTO receivers (Receiver_ID, Name, Type, City, Contact)
        VALUES (?, ?, ?, ?, ?)
    """, (row['Receiver_ID'], row['Name'], row['Type'], row['City'], row['Contact']))

conn.commit()

In [12]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS food_listings(
        Food_ID INT PRIMARY KEY,
        Food_Name VARCHAR(300),
        Quantity VARCHAR(20),
        Expiry_Date VARCHAR(20),
        Provider_ID INTEGER,
        Provider_Type VARCHAR(50),
        Location VARCHAR(50),
        Food_Type VARCHAR(50),
        Meal_Type VARCHAR(50)
    )
""")
conn.commit()

In [13]:
for index, row in food_listings.iterrows():
    cursor.execute("""
        INSERT OR IGNORE INTO food_listings (Food_ID, Food_Name, Quantity, Expiry_Date, Provider_ID, Provider_Type, Location, Food_Type, Meal_Type)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (row['Food_ID'], row['Food_Name'], row['Quantity'], row['Expiry_Date'], row['Provider_ID'],row['Provider_Type'], row['Location'], row['Food_Type'], row['Meal_Type']))

conn.commit()

In [14]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS claims(
        Claim_ID INT PRIMARY KEY,
        Food_ID INT,
        Receiver_ID INT,
        Status VARCHAR(20),   
        Timestamp VARCHAR(20)
    )
""")
conn.commit()

In [15]:
for index, row in claims.iterrows():
    cursor.execute("""
        INSERT OR IGNORE INTO claims (Claim_ID, Food_ID, Receiver_ID, Status, Timestamp)
        VALUES (?, ?, ?, ?, ?)
    """, (row['Claim_ID'], row['Food_ID'], row['Receiver_ID'], row['Status'], row['Timestamp']))

conn.commit()

In [16]:
cursor.execute("SELECT*FROM providers LIMIT 5")
print(cursor.fetchall())

[(1, 'Gonzales-Cochran', 'Supermarket', '74347 Christopher Extensions\nAndreamouth, OK 91839', 'New Jessica', '+1-600-220-0480'), (2, 'Nielsen, Johnson and Fuller', 'Grocery Store', '91228 Hanson Stream\nWelchtown, OR 27136', 'East Sheena', '+1-925-283-8901x6297'), (3, 'Miller-Black', 'Supermarket', '561 Martinez Point Suite 507\nGuzmanchester, WA 94320', 'Lake Jesusview', '001-517-295-2206'), (4, 'Clark, Prince and Williams', 'Grocery Store', '467 Bell Trail Suite 409\nPort Jesus, IA 61188', 'Mendezmouth', '556.944.8935x401'), (5, 'Coleman-Farley', 'Grocery Store', '078 Matthew Creek Apt. 319\nSaraborough, MA 53978', 'Valentineside', '193.714.6577')]

In [ ]:
# 1. How many food providers and receivers are there in each city?  
query = "SELECT CITY, COUNT (*) AS provider_count FROM providers GROUP BY City LIMIT 5"
provider_count = pd.read_sql_query(query,conn)
print(provider_count)

               City  provider_count
0          Adambury               1
1         Adamsview               1
2        Adamsville               1
3      Aguirreville               1
4  Alexanderchester               1

In [18]:
query = "SELECT City,COUNT (*) AS receiver_count FROM receivers GROUP BY city LIMIT 5"
receiver_count = pd.read_sql_query(query,conn)
print(receiver_count)

            City  receiver_count
0     Aaronshire               1
1       Adamland               1
2    Aguilarbury               1
3    Aguilarstad               1
4  Alexanderbury               1

In [19]:
providers.columns

Index(['Provider_ID', 'Name', 'Type', 'Address', 'City', 'Contact'], dtype='object')

In [20]:
# 2. Which type of food provider (restaurant, grocery store, etc.) contributes the most food? 
query = """
SELECT Provider_Type, 
SUM (Quantity) AS Total_Quantity 
FROM food_listings 
GROUP BY Provider_Type 
ORDER BY Total_Quantity DESC;
"""

high_contributor = pd.read_sql_query(query,conn)
print(high_contributor.head(1))

  Provider_Type  Total_Quantity
0    Restaurant            6923

In [21]:
providers.head()

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,+1-600-220-0480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,+1-925-283-8901x6297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,001-517-295-2206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,556.944.8935x401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,193.714.6577

In [22]:
# 3. What is the contact information of food providers in a specific city? 
city = 'New Jessica'
query = f"""
SELECT Name,Contact
FROM providers
WHERE City ='{city}';
"""

provider_city = pd.read_sql_query(query,conn)
print(provider_city)

               Name          Contact
0  Gonzales-Cochran  +1-600-220-0480

In [23]:
claims.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp'], dtype='object')

In [24]:
# 4. Which receivers have claimed the most food? 
query = """
SELECT receivers.Name,
SUM (food_listings.Quantity) AS total_claimed
FROM claims 
JOIN receivers ON claims.Receiver_ID = receivers.Receiver_ID
JOIN food_listings ON claims.Food_ID = food_listings.Food_ID
WHERE claims.Status = 'Completed'
GROUP BY receivers.Name
ORDER BY total_claimed DESC;
"""

top_receiver = pd.read_sql_query(query,conn)
print(top_receiver.head(1))

           Name  total_claimed
0  Derek Potter             99

In [25]:
# 5. What is the total quantity of food available from all providers?
query = """
SELECT 
SUM (food_listings.Quantity) AS Total_Quantity
FROM food_listings;
"""
total_food = pd.read_sql_query(query,conn)
print(total_food.head(1))

   Total_Quantity
0           25794

In [26]:
food_listings.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='object')

In [27]:
# 6. Which city has the highest number of food listings?
query = """
SELECT Location, COUNT (*) AS total_count
FROM food_listings
GROUP BY Location
ORDER BY total_count DESC
LIMIT 1
"""
total_count = pd.read_sql_query(query,conn)
print(total_count)

        Location  total_count
0  South Kathryn            6

In [28]:
# 7. What are the most commonly available food types? 
query = """
SELECT Food_Type, COUNT (*) as Most_Common
FROM food_listings
GROUP BY Food_Type
ORDER BY Most_Common DESC
LIMIT 1
"""
Most_Common = pd.read_sql_query(query,conn)
print(Most_Common)

    Food_Type  Most_Common
0  Vegetarian          336

In [29]:
food_listings.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='object')

In [30]:
claims.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp'], dtype='object')

In [31]:
# 8. How many food claims have been made for each food item? 
query = """
SELECT Food_Name, COUNT(*) AS No_of_Claims
FROM food_listings
LEFT JOIN Claims
ON food_listings.Food_ID = claims.Food_ID
GROUP BY food_listings.Food_Name
"""
Most_Claimed = pd.read_sql_query(query,conn)
print(Most_Claimed)

    Food_Name  No_of_Claims
0       Bread           128
1     Chicken           137
2       Dairy           148
3        Fish           139
4      Fruits           104
5       Pasta           128
6        Rice           155
7       Salad           142
8        Soup           153
9  Vegetables           119

In [32]:
claims.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp'], dtype='object')

In [33]:
receivers.columns

Index(['Receiver_ID', 'Name', 'Type', 'City', 'Contact'], dtype='object')

In [34]:
food_listings.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='object')

In [35]:
providers.columns

Index(['Provider_ID', 'Name', 'Type', 'Address', 'City', 'Contact'], dtype='object')

In [36]:
# 9. Which provider has had the highest number of successful food claims? 
query = """
SELECT providers.Provider_ID,providers.Name,
COUNT (*) AS Successful_Claims
FROM claims
LEFT JOIN food_listings
ON claims.Food_ID = food_listings.Food_ID
LEFT JOIN providers
ON food_listings.Provider_ID=providers.Provider_ID
WHERE claims.Status = 'Completed'
GROUP BY food_listings.Provider_ID
ORDER BY Successful_Claims DESC
 LIMIT 1
"""
Successfully_Claimed = pd.read_sql_query(query,conn)
print(Successfully_Claimed)

   provider_ID         Name  Successful_Claims
0          709  Barry Group                  5

In [ ]:
# 10. What percentage of food claims are completed vs. pending vs. canceled? 
query = """
SELECT Status, COUNT (*) * 100/(SELECT COUNT(*)FROM Claims)
AS Percentage
FROM claims
GROUP BY Status
"""
percentage_Claimed = pd.read_sql_query(query,conn)
print(percentage_Claimed)

      Status  Percentage
0  Cancelled          33
1  Completed          33
2    Pending          32

In [38]:
# 11. What is the average quantity of food claimed per receiver? 
query = """
SELECT receivers.Receiver_ID,receivers.Name,
Avg(food_listings.Quantity) AS Average_Quantity
FROM claims
JOIN receivers
ON claims.Receiver_ID = receivers.Receiver_ID 
JOIN food_listings
ON claims.Food_ID = food_listings.Food_ID
GROUP BY receivers.Receiver_ID,receivers.Name
"""

average_Claimed = pd.read_sql_query(query,conn)
print(average_Claimed)

     Receiver_ID              Name  Average_Quantity
0              1      Donald Gomez              35.5
1              2      Laurie Ramos              47.0
2              3      Ashley Mckee              26.0
3              4        Erika Rose              30.5
4              6  Mandy Sutton PhD              15.0
..           ...               ...               ...
619          995   Brittany Taylor              35.0
620          996    Matthew Curtis              24.5
621          997       Amanda Cain              25.5
622          999   Cheyenne Ramsey              42.0
623         1000      April Miller              19.0

[624 rows x 3 columns]

In [39]:
claims.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp'], dtype='object')

In [40]:
food_listings.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='object')

In [41]:
food_listings.head()

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
0,1,Bread,43,3/17/2025,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,3/24/2025,791,Grocery Store,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,3/28/2025,478,Catering Service,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,3/16/2025,930,Restaurant,Kellytown,Vegan,Lunch
4,5,Soup,14,3/19/2025,279,Restaurant,Garciaport,Vegan,Dinner

In [42]:
# 12. Which meal type (breakfast, lunch, dinner, snacks) is claimed the most?
query = """
SELECT food_listings.Meal_Type,
COUNT (*) AS most_claimed
FROM claims
JOIN food_listings
ON claims.Food_ID = food_listings.Food_ID
GROUP BY Meal_Type
ORDER BY Meal_Type DESC
LIMIT 1
"""
most_Claimed = pd.read_sql_query(query,conn)
print(most_Claimed)

  Meal_Type  most_claimed
0    Snacks           240

In [43]:
providers.columns

Index(['Provider_ID', 'Name', 'Type', 'Address', 'City', 'Contact'], dtype='object')

In [44]:
food_listings.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='object')

In [45]:
# 13. What is the total quantity of food donated by each provider? 
query = """
SELECT providers.Provider_ID,providers.Name,
sum(food_listings.Quantity) As Total_Quantity
FROM food_listings
LEFT JOIN providers
ON providers.Provider_ID = food_listings.Provider_ID
GROUP BY providers.Provider_ID,providers.Name
"""

Total_quantity = pd.read_sql_query(query,conn)
print(Total_quantity)

     provider_ID                         Name  Total_Quantity
0              1             Gonzales-Cochran              78
1              2  Nielsen, Johnson and Fuller              53
2              4   Clark, Prince and Williams              96
3              5               Coleman-Farley              92
4              7                    Ortiz-Lee             114
..           ...                          ...             ...
632          995                  Moore Group             106
633          997               Garza-Williams              47
634          998                  Novak Group               7
635          999                    Moody Ltd              57
636         1000               Jenkins-Brooks              47

[637 rows x 3 columns]

In [46]:
# 14. Which city has the highest number of different provider types?
query = """
SELECT City,
COUNT (DISTINCT Type) AS Different_Types
FROM providers
GROUP BY City
ORDER BY Different_Types DESC
LIMIT 1
"""
different_providers = pd.read_sql_query(query,conn)
print(different_providers)

                       City  Different_Types
0  South Christopherborough                3

In [47]:
food_listings.head()

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
0,1,Bread,43,3/17/2025,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,3/24/2025,791,Grocery Store,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,3/28/2025,478,Catering Service,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,3/16/2025,930,Restaurant,Kellytown,Vegan,Lunch
4,5,Soup,14,3/19/2025,279,Restaurant,Garciaport,Vegan,Dinner

In [48]:
# 15. List the top 5 food items with the largest total quantity listed?
query = """
SELECT Food_Name,sum(Quantity) AS Total_quantity
FROM food_listings
GROUP BY Food_Name
ORDER BY Total_quantity DESC
LIMIT 5
"""

high = pd.read_sql_query(query,conn)
print(high)

  Food_Name  Total_quantity
0      Rice            3133
1      Soup            2819
2     Salad            2765
3     Dairy            2765
4     Bread            2726

In [49]:
providers.head()

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,+1-600-220-0480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,+1-925-283-8901x6297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,001-517-295-2206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,556.944.8935x401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,193.714.6577

In [50]:
food_listings.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='object')

In [ ]:
# 16. How many providers have never listed any food?
query = """
SELECT providers.Provider_ID,providers.Name
FROM providers
LEFT JOIN food_listings
ON food_listings.Provider_ID = providers.Provider_ID
WHERE food_listings.Provider_ID IS NULL
"""
no_listing = pd.read_sql_query(query,conn)
print(no_listing)

     provider_ID                          Name
0              3                  Miller-Black
1              6                Lawson-Walters
2              8                  Curtis-Lewis
3             12                    Miller Ltd
4             13   Parker, Flores and Jennings
..           ...                           ...
358          988  Morris, Serrano and Roberson
359          991                   Spencer LLC
360          992                Miller-Sanders
361          994    Porter, Hernandez and Pace
362          996     Vasquez, Ruiz and Flowers

[363 rows x 2 columns]

In [52]:
# 16. How many providers have never listed any food?
query = """
SELECT COUNT (*) AS NO_LISTING
FROM providers
LEFT JOIN food_listings
ON food_listings.Provider_ID = providers.Provider_ID
WHERE food_listings.Provider_ID IS NULL
  
"""
no_listing = pd.read_sql_query(query,conn)
print(no_listing)

   NO_LISTING
0         363

In [53]:
receivers.columns

Index(['Receiver_ID', 'Name', 'Type', 'City', 'Contact'], dtype='object')

In [54]:
claims.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp'], dtype='object')

In [55]:
claims.head()

   Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
0         1      164          908    Pending    3/5/2025 5:26
1         2      353          391  Cancelled  3/11/2025 10:24
2         3      626          492  Completed   3/21/2025 0:59
3         4       61          933  Cancelled    3/4/2025 9:08
4         5      345          229    Pending  3/14/2025 15:17

In [56]:
# 17. Which receiver type (e.g., NGO, individual) has made the most completed claims?
query = """
SELECT receivers.Type,
COUNT (*) AS high_claim
FROM receivers
LEFT JOIN claims
ON receivers.Receiver_ID = claims.Receiver_ID
WHERE claims.Status ='Completed'
GROUP BY receivers.Type
ORDER BY high_claim
LIMIT 1

"""
top = pd.read_sql_query(query,conn)
print(top)

         Type  high_claim
0  Individual          72

In [57]:
# 18. What is the average quantity of food listed per provider?
query = """
SELECT food_listings.Provider_ID,providers.Name,
AVG(food_listings.Quantity) AS Average
FROM food_listings
LEFT JOIN providers
ON food_listings.Provider_ID = providers.Provider_ID
GROUP BY food_listings.Provider_ID

"""

avg = pd.read_sql_query(query,conn)
print(avg)

     Provider_ID                         Name  Average
0              1             Gonzales-Cochran     39.0
1              2  Nielsen, Johnson and Fuller     26.5
2              4   Clark, Prince and Williams     32.0
3              5               Coleman-Farley     46.0
4              7                    Ortiz-Lee     38.0
..           ...                          ...      ...
632          995                  Moore Group     26.5
633          997               Garza-Williams     47.0
634          998                  Novak Group      7.0
635          999                    Moody Ltd     28.5
636         1000               Jenkins-Brooks     47.0

[637 rows x 3 columns]

In [58]:
claims.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp'], dtype='object')

In [59]:
food_listings.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='object')

In [60]:
# 19. Which food type is claimed the most?
query = """
SELECT food_listings.Food_Type, 
COUNT (*) Most_Claimed
FROM claims
LEFT JOIN food_listings
ON food_listings.Food_ID = claims.Food_ID
GROUP BY food_listings.Food_Type
LIMIT 1
"""
high = pd.read_sql_query(query,conn)
print(high)

        Food_Type  Most_Claimed
0  Non-Vegetarian           331

In [ ]:
# 20. Are there any food listings that have never been claimed?
query = """
SELECT food_listings.Food_Name,
COUNT (claims.Food_ID) AS Never_Claimed
FROM food_listings
LEFT JOIN claims
ON food_listings.Food_ID = claims.Food_ID
WHERE claims.Food_ID IS NULL
GROUP BY food_listings.Food_Name
"""
never = pd.read_sql_query(query,conn)
print(never)

    Food_Name  Never_Claimed
0       Bread              0
1     Chicken              0
2       Dairy              0
3        Fish              0
4      Fruits              0
5       Pasta              0
6        Rice              0
7       Salad              0
8        Soup              0
9  Vegetables              0